### ISSUE TITLE
Avoid empty strings in config files to be used as valid ones

### ISSUE THREAD

**Issue by aletundo** [StackStorm-Exchange/stackstorm-kubernetes#28]
Hello!

I spent hours dealing with an HTTP 403 error since I filled the cert and key path and I left the user field as an empty string. At [line 36](https://github.com/StackStorm-Exchange/stackstorm-kubernetes/blob/master/actions/lib/k8s.py#L36) of the `actions/lib/k8s.py` file the if condition is verified and it tries to use the basic auth rather than set `self.clientcert` to `1`.

The README states: _Only user and password or client_cert_path (key is optional) need to be set for this to work_. IMHO, it's confusing.

I suggest to update the README or to make the if conditions more conservatives. I can provide a PR if you want :)

**Comment by LindsayHill** [comment]
@aletundo by all means, please submit a PR. Happy to take PRs and improve things

**Comment by aletundo** [comment]
@LindsayHill For sure! I just forked the repository. I will provide a PR in a couple of days.
