### ISSUE TITLE
Support for token based authentication

### ISSUE THREAD

**Issue by uttamk** [StackStorm-Exchange/stackstorm-kubernetes#33]
Currently, the pack supports certificates and username/password based authentication.  The k8s cluster we use just supports token based authentication for external clients as a policy. It would be awesome if the kubernetes pack supported token based authentication.

**Comment by uttamk** [comment]
https://github.com/StackStorm-Exchange/stackstorm-kubernetes/pull/34 adds the capability of using bearer token based authentication.

**Comment by LindsayHill** [comment]
Resolved by #34
